In [1]:
import pandas as pd

In [4]:
df = pd.read_html('https://fbref.com/en/comps/182/NWSL-Stats', 
                  attrs={"id" : "results20241821_overall"})[0]

In [6]:
df.head()

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Pride,10,7,3,0,18,9,9,24,2.4,17.3,10.0,7.4,0.74,W W W W W,6473,Barbra Banda - 6,Anna Moorhouse,NaN
1,2,Current,10,6,4,0,25,15,10,22,2.2,21.1,9.8,11.3,1.13,W D D W D,6900,Temwa Chawinga - 5,Adrianna Franch,NaN
2,3,Spirit,10,7,0,3,22,14,8,21,2.1,17.5,11.3,6.2,0.62,L W L W W,7996,"Ouleymata Sarr, Croix Bethune - 4",Aubrey Kingsbury,NaN
3,4,Thorns,10,6,1,3,23,14,9,19,1.9,16.3,13.0,3.3,0.33,W W W W W,18279,Sophia Smith - 8,Shelby Hogan,NaN
4,5,Red Stars,10,5,1,4,15,14,1,16,1.6,13.4,13.8,-0.4,-0.04,L L W W L,2763,Allyson Schlegel - 4,Alyssa Naeher,NaN

In [7]:
df = df.dropna(subset=['Rk'])

In [8]:
df.head()

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Pride,10,7,3,0,18,9,9,24,2.4,17.3,10.0,7.4,0.74,W W W W W,6473,Barbra Banda - 6,Anna Moorhouse,NaN
1,2,Current,10,6,4,0,25,15,10,22,2.2,21.1,9.8,11.3,1.13,W D D W D,6900,Temwa Chawinga - 5,Adrianna Franch,NaN
2,3,Spirit,10,7,0,3,22,14,8,21,2.1,17.5,11.3,6.2,0.62,L W L W W,7996,"Ouleymata Sarr, Croix Bethune - 4",Aubrey Kingsbury,NaN
3,4,Thorns,10,6,1,3,23,14,9,19,1.9,16.3,13.0,3.3,0.33,W W W W W,18279,Sophia Smith - 8,Shelby Hogan,NaN
4,5,Red Stars,10,5,1,4,15,14,1,16,1.6,13.4,13.8,-0.4,-0.04,L L W W L,2763,Allyson Schlegel - 4,Alyssa Naeher,NaN

In [9]:
df = pd.read_html('https://fbref.com/en/squads/85c458aa/North-Carolina-Courage-Stats',
                 attrs={"id": "stats_standard_182"})[0]

In [10]:
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0      Kaleigh Kurtz             us USA                 DF             26-254
1       Casey Murphy             us USA                 GK             28-025
2      Ryan Williams             us USA                 DF             28-087
3    Felicitas Rauch             de GER                 DF             28-020
4     Ashley Sanchez             us USA                 MF             25-065

  Playing Time                     Performance       ... Per 90 Minutes        \
            MP Starts    Min   90s         Gls  Ast  ...            Ast   G+A
0           10     10  900.0  10.0         1.0  0.0  ...           0.00  0.10
1           10     10  900.0  10.0         0.0  0.0  ...           0.00  0.00
2           10     10  900.0  10.0         0.0  0.0  ...           0.00  0.00
3           10     10  865.0   9.6         0.0  0.0  ...           0.00  0.00
4           10     10  856.0   9.5         1.0  3.0  ...           0.32  0.42

                                                 Unnamed: 33_level_0
   G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG             Matches
0  0.10   0.10  0.07  0.02   0.09  0.07     0.09             Matches
1  0.00   0.00  0.00  0.00   0.00  0.00     0.00             Matches
2  0.00   0.00  0.00  0.14   0.14  0.00     0.14             Matches
3  0.00   0.00  0.02  0.03   0.05  0.02     0.05             Matches
4  0.11   0.42  0.23  0.34   0.57  0.23     0.57             Matches

[5 rows x 34 columns]

In [11]:
df.columns.values

array([('Unnamed: 0_level_0', 'Player'), ('Unnamed: 1_level_0', 'Nation'),
       ('Unnamed: 2_level_0', 'Pos'), ('Unnamed: 3_level_0', 'Age'),
       ('Playing Time', 'MP'), ('Playing Time', 'Starts'),
       ('Playing Time', 'Min'), ('Playing Time', '90s'),
       ('Performance', 'Gls'), ('Performance', 'Ast'),
       ('Performance', 'G+A'), ('Performance', 'G-PK'),
       ('Performance', 'PK'), ('Performance', 'PKatt'),
       ('Performance', 'CrdY'), ('Performance', 'CrdR'),
       ('Expected', 'xG'), ('Expected', 'npxG'), ('Expected', 'xAG'),
       ('Expected', 'npxG+xAG'), ('Progression', 'PrgC'),
       ('Progression', 'PrgP'), ('Progression', 'PrgR'),
       ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'),
       ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'),
       ('Per 90 Minutes', 'G+A-PK'), ('Per 90 Minutes', 'xG'),
       ('Per 90 Minutes', 'xAG'), ('Per 90 Minutes', 'xG+xAG'),
       ('Per 90 Minutes', 'npxG'), ('Per 90 Minutes', 'npxG+xAG'),
       ('Unnamed: 33_level_0', 'Matches')], dtype=object)

In [13]:
df.columns = ['_'.join(col).strip() for col in df.columns.values]

In [14]:
df.head()

,Unnamed: 0_level_0_Player,Unnamed: 1_level_0_Nation,Unnamed: 2_level_0_Pos,Unnamed: 3_level_0_Age,Playing Time_MP,Playing Time_Starts,Playing Time_Min,Playing Time_90s,Performance_Gls,Performance_Ast,...,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Per 90 Minutes_xG,Per 90 Minutes_xAG,Per 90 Minutes_xG+xAG,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xAG,Unnamed: 33_level_0_Matches
0,Kaleigh Kurtz,us USA,DF,26-254,10,10,900.0,10.0,1.0,0.0,...,0.00,0.10,0.10,0.10,0.07,0.02,0.09,0.07,0.09,Matches
1,Casey Murphy,us USA,GK,28-025,10,10,900.0,10.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
2,Ryan Williams,us USA,DF,28-087,10,10,900.0,10.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.14,0.14,0.00,0.14,Matches
3,Felicitas Rauch,de GER,DF,28-020,10,10,865.0,9.6,0.0,0.0,...,0.00,0.00,0.00,0.00,0.02,0.03,0.05,0.02,0.05,Matches
4,Ashley Sanchez,us USA,MF,25-065,10,10,856.0,9.5,1.0,3.0,...,0.32,0.42,0.11,0.42,0.23,0.34,0.57,0.23,0.57,Matches